---
- name: "Playing with Ansible "
  hosts: localhost
  connection: local 
  tasks:

    - name: Enable amazon-linux-extras packages
      shell: amazon-linux-extras enable nginx1

    - name: Installs Nginx web server
      yum: pkg=nginx state=present

    - name: Create default index page
      copy:
        dest: /usr/share/nginx/html/index.html
        content: "If you see this message, Ansible successfully installed nginx. The secret retrieved from Hashicrop Vault is: {{ valut_data }}"

    - name: start Nginx
      service: name=nginx state=started
